apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: flask-app
        image: dedinededin/flask-app:b74edb444397b8d681130f3c43284c63ab052891  # This will be updated by the pipeline
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m" 