apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: development

resources:
  - ../../base/nginx    # Nginx base directory
  - ../../base/flask-app  # Flask app base directory

patches:
  - path: nginx-patch.yaml
  - path: flask-patch.yaml 
