apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: http-echo-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ibrahim-dogan/argo-cd-poc.git
    targetRevision: HEAD
    path: manifests/http-echo/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http-echo
  template:
    metadata:
      labels:
        app: http-echo
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo:latest
        args:
        - "-text=Hello, ArgoCD!"
        ports:
        - containerPort: 5678
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 3
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: http-echo
  namespace: prod
spec:
  selector:
    app: http-echo
  ports:
  - port: 80
    targetPort: 5678
  type: ClusterIP 