apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: json-server-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ibrahim-dogan/argo-cd-poc.git
    targetRevision: HEAD
    path: apps/prod
    directory:
      include: json-server.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-server
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: json-server
  template:
    metadata:
      labels:
        app: json-server
    spec:
      containers:
      - name: json-server
        image: clue/json-server:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "400m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: json-server
  namespace: prod
spec:
  selector:
    app: json-server
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP 