apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-express-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ibrahim-dogan/argo-cd-poc.git
    targetRevision: HEAD
    path: manifests/node-express/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-express
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-express
  template:
    metadata:
      labels:
        app: node-express
    spec:
      containers:
      - name: node-express
        image: public.ecr.aws/docker/library/node-express:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "400m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: node-express
  namespace: prod
spec:
  selector:
    app: node-express
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP 