apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  project: default
  source:
    repoURL: https://github.com/ibrahim-dogan/argo-cd-poc.git
    path: nginx/overlays/dev
  destination:
    namespace: dev 