apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todomvc-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ibrahim-dogan/argo-cd-poc.git
    targetRevision: HEAD
    path: manifests/todomvc-app/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todomvc-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todomvc-app
  template:
    metadata:
      labels:
        app: todomvc-app
    spec:
      containers:
      - name: todomvc-app
        image: ghcr.io/docker-library/todomvc-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: todomvc-app
  namespace: dev
spec:
  selector:
    app: todomvc-app
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP 